### PR TITLE
Delete folder cache (fixes #42 #48 #49)

### LINKED ISSUE #42: We recommend using WhatsApp Web with one of the following browsers:
From Today, Whats app is asking to use one off the browsers and don't let the app continue to be used

### PR DESCRIPTION
**Pull request by gutierri**
Solves the problem of updating the browser

### CODE REVIEW

**Comment by sparkbuzz** [comment]
Hi, I tried your fork on Mac Yosemite, but it doesn't appear to resolve the problem. I still get the screen telling you which browsers are supported.

**Comment by saxonbeta** [comment]
This patch does not resolve the problem under linux :(

**Comment by gutierri** [comment]
I'll review it

**Comment by MrOutis** [comment]
Check this out: https://github.com/Aluxian/WhatsApp-Desktop/issues/74#issuecomment-154445299

**Comment by gutierri** [comment]
@MrOutis Sorry, I was out of time. I will stop to look calmly and fix it properly.

**Comment by gutierri** [comment]
@MrOutis See if this repository solves problems https://github.com/zweicoder/Sup-for-WhatsApp

**Comment by Aluxian** [comment]
Fixed in Whatsie by cleaning the user agent: https://github.com/Aluxian/Whatsie

**Pull request closed without merging**
